### ISSUE TITLE
Build error with Angular 5

### ISSUE THREAD

**Issue by alsoicode** [plauzul/ng2-izitoast#3]
When implementing ng2-izitoast in an Angular 5 project, I get the following build error when running `ng serve`:

ERROR in ./node_modules/ng2-izitoast/index.ts
Module build failed: Error: /Users/btaylor/work/angular-apps/dz-angular/node_modules/ng2-izitoast/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/Users/btaylor/work/angular-apps/dz-angular/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (/Users/btaylor/work/angular-apps/dz-angular/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 21:0-49
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by Albejr** [comment]
Same error, Any solution?

ERROR in ./node_modules/ng2-izitoast/src/ng2-izitoast.component.ts

**Comment by n3nikita** [comment]
I got the same error.

`./node_modules/ng2-izitoast/index.ts
Module build failed: Error: TODOapp\node_modules\ng2-izitoast\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (TODOapp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (TODOapp\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 22:0-49
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

**Comment by daniel-van-niekerk** [comment]
According to this CLI issue:
[https://github.com/angular/angular-cli/issues/8284](https://github.com/angular/angular-cli/issues/8284)

The issue is that the CLI does not build your typescript files. It expects to find compiled JS files in node_modules..

It seems there are ways to force the CLI to include these TS files but it is bad practice because the typescript version you use might be different from what the author used and could produce different results.

**Comment by paulohrdev** [comment]
I'll take a look

**Comment by elSuperRiton** [comment]
+1 after upgrading to angular 5. 
I've managed to solve it by adding "../node_modules/ng2-izitoast/index.ts" to the tsconfig file but for some strange reason it doesn't work anymore ...

**Comment by Albejr** [comment]
Possibly the same error, resolved: [https://github.com/matheushf/ng2-date-countdown/issues/3](https://github.com/matheushf/ng2-date-countdown/issues/3)

**Comment by wilcotroost** [comment]
+1 when installing on angular 5.
Adding the file to the tsconfigs did not fix the issue.

**Comment by LucasViniciusPereira** [comment]
I tried install, but angular 5 not works.

**Comment by mohammadkhoeini** [comment]
++
