### ISSUE TITLE
1.0.1 fail on angular 4

### ISSUE THREAD

**Issue by arthurhamon** [plauzul/ng2-izitoast#5]
Hi, you update your repo yesterday, to version 1.0.1 but you make major change so please update to version 2.0.0 for Angular 5 and stay at 1.0.0 for Angular 2 & 4

Thank you

**Comment by arthurhamon** [comment]
And read this doc for information about versioning 
https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by paulohrdev** [comment]
my next versions will follow this pattern

**Comment by arthurhamon** [comment]
@plauzul Thank you :)
